### ISSUE TITLE
pip error while installing

### ISSUE THREAD

**Issue by tin2tin** [resemble-ai/resemble-enhance#1]
I tried using the enhancer on a bark audio file, and it works wonders!

Trying to pip install it, I get this error:

```
>>> ERROR
1
  error: subprocess-exited-with-error

  python setup.py egg_info did not run successfully.
  exit code: 1

  [15 lines of output]
  test.c
  LINK : fatal error LNK1181: cannot open input file 'aio.lib'
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\45239\AppData\Local\Temp\pip-install-phvt4rr_\deepspeed_96322bcee24e46919b71c01d496a21e7\setup.py", line 182, in <module>
      abort(f"Unable to pre-compile {op_name}")
    File "C:\Users\45239\AppData\Local\Temp\pip-install-phvt4rr_\deepspeed_96322bcee24e46919b71c01d496a21e7\setup.py", line 52, in abort
      assert False, msg
  AssertionError: Unable to pre-compile async_io
  DS_BUILD_OPS=1
   [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
   [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
   [WARNING]  One can disable async_io with DS_BUILD_AIO=0
   [ERROR]  Unable to pre-compile async_io
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by Sarakael78** [comment]
Try installing on ubuntu (WSL) and an environment, worked for me

**Comment by tin2tin** [comment]
I'm on Windows...

**Comment by Sarakael78** [comment]
https://learn.microsoft.com/en-us/windows/wsl/install

**Comment by daswer123** [comment]
@tin2tin 
Problem because of deepspeed, I was able to use this guide to build a wheel for windows and run resemble-enhance on windows
check this guide https://github.com/erew123/alltalk_tts?tab=readme-ov-file#-option-2---a-bit-more-complicated

**Comment by tin2tin** [comment]
@daswer123 Excellent. Thank you very much for the deepspeed wheel. That makes it possible to install it on Windows. 

I noticed that you have been specifying the torch/vision/audio version too. This makes sense, since the version it comes with as a requirement doesn't include CUDA(for me).

**Comment by oliverban** [comment]
> @tin2tin The problem is due to deepspeed, the authors don't support python above 3.9 for windows
> 
> I was able to use this guide to build a wheel for windows and run resemble-enhance on windows check this guide https://github.com/erew123/alltalk_tts?tab=readme-ov-file#-option-2---a-bit-more-complicated
> 
> UPD: Made a fork where you can try this wonder technology on windows https://github.com/daswer123/resemble-enhance-windows

Awesome! Thanks so much for the fork! <3

**Comment by Kuiriel** [comment]
Oof, I wish you were pinned on the front page so I could've saved half an hour of installing packages trying to work out what was borked. Thank you for the fork.

**Comment by mr-akashjain** [comment]
how can I do bulk audio now?

**Comment by 6630507** [comment]
@daswer123

Thanks for identifying the problem!  I was having this issue on Linux with python 3.13.   I was able to install on Linux with Python 3.10
