### ISSUE TITLE
PosixPath error when running on MacOS

### ISSUE THREAD

**Issue by symbion6** [resemble-ai/resemble-enhance#11]
Trying to run on MacOS, but to no avail.
I've placed a "1.wav" file in the current folder and start resemble-enhance like this:
resemble-enhance ./ ./
The same output is given when using an absolute path.

Output:

```
[2024-01-03 20:17:18,615] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to mps (auto detect)
[2024-01-03 20:17:18,938] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
CUDA is not available but --device is set to cuda, using CPU instead
Processing 1.wav:   0%|                                   | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/resemble-enhance", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/resemble_enhance/enhancer/__main__.py", line 100, in main
    dwav, sr = torchaudio.load(path)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torchaudio/_backend/utils.py", line 204, in load
    return backend.load(uri, frame_offset, num_frames, normalize, channels_first, format, buffer_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torchaudio/_backend/sox.py", line 42, in load
    ret = torch.ops.torchaudio.sox_io_load_audio_file(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/_ops.py", line 692, in __call__
    return self._op(*args, **kwargs or {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: torchaudio::sox_io_load_audio_file() Expected a value of type 'str' for argument '_0' but instead found type 'PosixPath'.
Position: 0
Value: PosixPath('1.wav')
Declaration: torchaudio::sox_io_load_audio_file(str _0, int? _1, int? _2, bool? _3, bool? _4, str? _5) -> (Tensor _0, int _1)
Cast error details: Unable to cast Python instance of type <class 'pathlib.PosixPath'> to C++ type '?' (#define PYBIND11_DETAILED_ERROR_MESSAGES or compile in debug mode for details)
```

**Comment by MisakaMikoto96** [comment]
same

**Comment by JonathanBonnaud** [comment]
Hello, any update on this issue? I am getting the same error

**Comment by HninLwin-byte** [comment]
hello I got this error while running on Mac OS , I got nothing , just this 
![Screenshot 2567-03-28 at 02 59 41 (2)](https://github.com/resemble-ai/resemble-enhance/assets/65151308/7422bfd2-662e-4c07-a4fa-b62a32966bd7)

**Comment by fah** [comment]
This error occures because:

Cit.: "... Starting version 2.1, TorchAudio official binary distributions are compatible with FFmpeg version 6, 5 and 4. (>=4.4, <7) ..."  
(See: https://pytorch.org/audio/2.1.0/installation.html ) 

With
```sh
pip3 freeze|grep torchaudio
```
you can check your version.


To fix it in MacOS 13.6.4 I relinked the former ffmpeg@7 with ffmpeg@6 like so:
```sh
% ls -la /usr/local/bin/ffmpeg
lrwxr-xr-x  1 f  admin  33 22 Jun 18:35 /usr/local/bin/ffmpeg -> ../Cellar/ffmpeg/7.0.1/bin/ffmpeg
% brew link --overwrite ffmpeg@6
Linking /usr/local/Cellar/ffmpeg@6/6.1.1_2... 458 symlinks created.
...
```

Then I did not get the POSIX error anymore:
```sh
% resemble-enhance --device cpu  "input" "output"
[2024-07-20 23:07:59,951] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to mps (auto detect)
[2024-07-20 23:08:00,191] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
Processing output/audio.wav:   0%|                                                                                                                                          | 0/1 [00:00<?, ?it/s]Klone nach './venv/lib/python3.10/site-packages/resemble_enhance/model_repo'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (39/39), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 40 (delta 12), reused 0 (delta 0), pack-reused 1 (from 1)
Entpacke Objekte: 100% (40/40), 5.47 KiB | 175.00 KiB/s, fertig.
Downloading LFS objects: 100% (4/4), 810 MB | 8.3 MB/s       
...
```

So my problem was that I had the ffmpeg version 6 already installed. But the applicaiton seems not o look for the binary at the right place (in my case in the Cellar of brew). 

See also "export TORCHAUDIO_USE_FFMPEG_VERSION=x" with x=0,4,5,6 these version are supported and then searched, see link above for details, too.
