### ISSUE TITLE
Docker installation possible?

### ISSUE THREAD

**Issue by liferadioat** [resemble-ai/resemble-enhance#12]
Hi,

is there a docker image, which you can provide for an easy installation?

Regards,

**Comment by TheNymon** [comment]
This Dockerfile generates an image for a container hosting the Gradio web application accessible at http://localhost:7860/

```Dockerfile
FROM python:3.11-slim
WORKDIR /app
RUN apt-get update && apt-get install -y git
RUN git clone -b main https://github.com/resemble-ai/resemble-enhance /app/resemble-enhance
WORKDIR /app/resemble-enhance
RUN pip install -e .
EXPOSE 7860
ENV GRADIO_SERVER_NAME="0.0.0.0"
CMD ["python", "app.py"]
```

To build the Docker image, simply execute the following command in the directory containing the Dockerfile:

```bash
docker build -t resemble-enhance .
```
Once the image is built, you can run it with GPU enabled using this command:

```bash
docker run -p 7860:7860 --gpus all --name resemble-enhance resemble-enhance
```

**Comment by liferadioat** [comment]
> This Dockerfile generates an image for a container hosting the Gradio web application accessible at http://localhost:7860/
> 
> ```dockerfile
> FROM python:3.11-slim
> WORKDIR /app
> RUN apt-get update && apt-get install -y git
> RUN git clone -b main https://github.com/resemble-ai/resemble-enhance /app/resemble-enhance
> WORKDIR /app/resemble-enhance
> RUN pip install -e .
> EXPOSE 7860
> ENV GRADIO_SERVER_NAME="0.0.0.0"
> CMD ["python", "app.py"]
> ```
> 
> To build the Docker image, simply execute the following command in the directory containing the Dockerfile:
> 
> ```shell
> docker build -t resemble-enhance .
> ```
> 
> Once the image is built, you can run it with GPU enabled using this command:
> 
> ```shell
> docker run -p 7860:7860 --gpus all --name resemble-enhance resemble-enhance
> ```

Thanks - docker run gives me: docker:  `Error response from daemon: could not select device driver "" with capabilities: [[gpu]]`. Is this container for cpu usage?

**Comment by liferadioat** [comment]
Thanks, got it working

**Comment by liferadioat** [comment]
In this docker example it seems that there is missing anything. I get the following error within the docker container - I´m using an ubuntu server with nvidia cuda right now:
```
deepspeed.ops.op_builder.builder.MissingCUDAException: CUDA_HOME does not exist, unable to compile CUDA op(s)
[2024-07-09 05:52:17,215] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
Traceback (most recent call last):
  File "/app/resemble-enhance/app.py", line 5, in <module>
    from resemble_enhance.enhancer.inference import denoise, enhance
  File "/app/resemble-enhance/resemble_enhance/enhancer/inference.py", line 9, in <module>
    from .train import Enhancer, HParams
  File "/app/resemble-enhance/resemble_enhance/enhancer/train.py", line 8, in <module>
    from deepspeed import DeepSpeedConfig
  File "/usr/local/lib/python3.11/site-packages/deepspeed/__init__.py", line 25, in <module>
    from . import ops
  File "/usr/local/lib/python3.11/site-packages/deepspeed/ops/__init__.py", line 15, in <module>
    from ..git_version_info import compatible_ops as __compatible_ops__
  File "/usr/local/lib/python3.11/site-packages/deepspeed/git_version_info.py", line 29, in <module>
    op_compatible = builder.is_compatible()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/deepspeed/ops/op_builder/fp_quantizer.py", line 29, in is_compatible
    sys_cuda_major, _ = installed_cuda_version()
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/deepspeed/ops/op_builder/builder.py", line 50, in installed_cuda_version
    raise MissingCUDAException("CUDA_HOME does not exist, unable to compile CUDA op(s)")
deepspeed.ops.op_builder.builder.MissingCUDAException: CUDA_HOME does not exist, unable to compile CUDA op(s)

```

**Comment by Zheone9** [comment]
> In this docker example it seems that there is missing anything. I get the following error within the docker container - I´m using an ubuntu server with nvidia rtx right now:
> 
> ```
> deepspeed.ops.op_builder.builder.MissingCUDAException: CUDA_HOME does not exist, unable to compile CUDA op(s)
> [2024-07-09 05:52:17,215] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
>  [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
>  [WARNING]  async_io: please install the libaio-dev package with apt
>  [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
>  [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
> Traceback (most recent call last):
>   File "/app/resemble-enhance/app.py", line 5, in <module>
>     from resemble_enhance.enhancer.inference import denoise, enhance
>   File "/app/resemble-enhance/resemble_enhance/enhancer/inference.py", line 9, in <module>
>     from .train import Enhancer, HParams
>   File "/app/resemble-enhance/resemble_enhance/enhancer/train.py", line 8, in <module>
>     from deepspeed import DeepSpeedConfig
>   File "/usr/local/lib/python3.11/site-packages/deepspeed/__init__.py", line 25, in <module>
>     from . import ops
>   File "/usr/local/lib/python3.11/site-packages/deepspeed/ops/__init__.py", line 15, in <module>
>     from ..git_version_info import compatible_ops as __compatible_ops__
>   File "/usr/local/lib/python3.11/site-packages/deepspeed/git_version_info.py", line 29, in <module>
>     op_compatible = builder.is_compatible()
>                     ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/deepspeed/ops/op_builder/fp_quantizer.py", line 29, in is_compatible
>     sys_cuda_major, _ = installed_cuda_version()
>                         ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/deepspeed/ops/op_builder/builder.py", line 50, in installed_cuda_version
>     raise MissingCUDAException("CUDA_HOME does not exist, unable to compile CUDA op(s)")
> deepspeed.ops.op_builder.builder.MissingCUDAException: CUDA_HOME does not exist, unable to compile CUDA op(s)
> ```

SAME, HELP

**Comment by Zheone9** [comment]
> Thanks, got it working

did u solve it?

**Comment by TheNymon** [comment]
The eternal "works on my machine" struggle. I thought Docker was supposed to save us from this xD
I only tested this on Windows 11 with WSL2, so there might be some quirks on your setup.

Are you sure your [CUDA Toolkit](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=20.04&target_type=deb_local) and[ NVIDIA Container Toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html) are properly installed on your Ubuntu Server?

One more thing you might want to try is switching the base image to one that already comes with a properly set up CUDA environment.

**Comment by liferadioat** [comment]
Thanks can you please provide an example?

**Comment by TheNymon** [comment]
I've made some modifications to the Dockerfile, and it seems to be working on my setup. Feel free to give it a try and see if it resolves your issue.

```Dockerfile
# Use NVIDIA CUDA development image based on Ubuntu 20.04
FROM nvidia/cuda:11.7.1-devel-ubuntu20.04  

# Set non-interactive mode to avoid prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive  

# Install required dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        software-properties-common \
        git \
        libaio-dev \
        build-essential && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        python3.11 \
        python3.11-venv \
        python3.11-dev \
        python3.11-distutils && \
    rm -rf /var/lib/apt/lists/*  

# Set Python 3.11 as the default
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.11 1  

# Upgrade pip
RUN python -m ensurepip --upgrade && \
    python -m pip install --upgrade pip  

# Set working directory
WORKDIR /app  

# Clone the repository
RUN git clone -b main https://github.com/resemble-ai/resemble-enhance /app/resemble-enhance  

# Install the package in editable mode
WORKDIR /app/resemble-enhance  
RUN pip install -e .  

# Expose the port for Gradio
EXPOSE 7860  

# Ensure Gradio listens on all interfaces
ENV GRADIO_SERVER_NAME="0.0.0.0"  

# Run the application
CMD ["python", "app.py"]  

``` 
Once you've built the image, you can run the container just as I described in my first post.

**Comment by Zheone9** [comment]
> I've made some modifications to the Dockerfile, and it seems to be working on my setup. Feel free to give it a try and see if it resolves your issue.
> 
> # Use NVIDIA CUDA development image based on Ubuntu 20.04
> FROM nvidia/cuda:11.7.1-devel-ubuntu20.04  
> 
> # Set non-interactive mode to avoid prompts during package installation
> ENV DEBIAN_FRONTEND=noninteractive  
> 
> # Install required dependencies
> RUN apt-get update && \
>     apt-get install -y --no-install-recommends \
>         software-properties-common \
>         git \
>         libaio-dev \
>         build-essential && \
>     add-apt-repository -y ppa:deadsnakes/ppa && \
>     apt-get update && \
>     apt-get install -y --no-install-recommends \
>         python3.11 \
>         python3.11-venv \
>         python3.11-dev \
>         python3.11-distutils && \
>     rm -rf /var/lib/apt/lists/*  
> 
> # Set Python 3.11 as the default
> RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.11 1  
> 
> # Upgrade pip
> RUN python -m ensurepip --upgrade && \
>     python -m pip install --upgrade pip  
> 
> # Set working directory
> WORKDIR /app  
> 
> # Clone the repository
> RUN git clone -b main https://github.com/resemble-ai/resemble-enhance /app/resemble-enhance  
> 
> # Install the package in editable mode
> WORKDIR /app/resemble-enhance  
> RUN pip install -e .  
> 
> # Expose the port for Gradio
> EXPOSE 7860  
> 
> # Ensure Gradio listens on all interfaces
> ENV GRADIO_SERVER_NAME="0.0.0.0"  
> 
> # Run the application
> CMD ["python", "app.py"]  
> Once you've built the image, you can run the container just as I described in my first post.

![Image](https://github.com/user-attachments/assets/312047d7-02dc-4827-8a5d-ef6c8ed70ce5)
still not working, I give up 😔. No error is displayed in the console.

**Comment by TheNymon** [comment]
> ![Image](https://github.com/user-attachments/assets/312047d7-02dc-4827-8a5d-ef6c8ed70ce5)
> still not working, I give up 😔. No error is displayed in the console.

That's sad. Especially if there aren't any logs :(

**Comment by cypher-256** [comment]
> I've made some modifications to the Dockerfile, and it seems to be working on my setup. Feel free to give it a try and see if it resolves your issue.
> 
> # Use NVIDIA CUDA development image based on Ubuntu 20.04
> FROM nvidia/cuda:11.7.1-devel-ubuntu20.04  
> 
> # Set non-interactive mode to avoid prompts during package installation
> ENV DEBIAN_FRONTEND=noninteractive  
> 
> # Install required dependencies
> RUN apt-get update && \
>     apt-get install -y --no-install-recommends \
>         software-properties-common \
>         git \
>         libaio-dev \
>         build-essential && \
>     add-apt-repository -y ppa:deadsnakes/ppa && \
>     apt-get update && \
>     apt-get install -y --no-install-recommends \
>         python3.11 \
>         python3.11-venv \
>         python3.11-dev \
>         python3.11-distutils && \
>     rm -rf /var/lib/apt/lists/*  
> 
> # Set Python 3.11 as the default
> RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.11 1  
> 
> # Upgrade pip
> RUN python -m ensurepip --upgrade && \
>     python -m pip install --upgrade pip  
> 
> # Set working directory
> WORKDIR /app  
> 
> # Clone the repository
> RUN git clone -b main https://github.com/resemble-ai/resemble-enhance /app/resemble-enhance  
> 
> # Install the package in editable mode
> WORKDIR /app/resemble-enhance  
> RUN pip install -e .  
> 
> # Expose the port for Gradio
> EXPOSE 7860  
> 
> # Ensure Gradio listens on all interfaces
> ENV GRADIO_SERVER_NAME="0.0.0.0"  
> 
> # Run the application
> CMD ["python", "app.py"]  
> Once you've built the image, you can run the container just as I described in my first post.

Hello,

Thank you for sharing your updated Dockerfile. I built the image and ran the container, but I’m still encountering this runtime error when loading WAV files:

```
soundfile.LibsndfileError: Error opening '/tmp/gradio/.../clase_1.wav': System error.
```

It looks like the native **libsndfile** library isn’t present in the image. To resolve this, you can add `libsndfile1` (and optionally `libsndfile1-dev`) to your `apt-get install` step. For example:

```dockerfile
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        software-properties-common \
        git \
        libaio-dev \
        build-essential \
        ffmpeg \
        sox \
        libsndfile1 \
        libsndfile1-dev && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        python3.11 \
        python3.11-venv \
        python3.11-dev \
        python3.11-distutils && \
    rm -rf /var/lib/apt/lists/*
```

After rebuilding with those packages, `torchaudio.load()` successfully opens WAV files. Please give it a try and let me know if this fixes the issue on your setup.

Kind regards,
cypher_256.
