### ISSUE TITLE
run the project meets errors

### ISSUE THREAD

**Issue by JackLau1222** [resemble-ai/resemble-enhance#17]
I use two methods to try to run the project
1. I download the project latest source code,and I use pip download all of dependencies,but i meet the error.BTW,the environment is python3.9 and i use Conda virtual environment
```bash
(voice_enhance) root@jack-B450M-S2H:~/project/resemble-enhance# python3 app.py 
Traceback (most recent call last):
  File "/root/project/resemble-enhance/app.py", line 5, in <module>
    from resemble_enhance.enhancer.inference import denoise, enhance
  File "/root/project/resemble-enhance/resemble_enhance/enhancer/inference.py", line 7, in <module>
    from ..inference import inference
  File "/root/project/resemble-enhance/resemble_enhance/inference.py", line 11, in <module>
    from .hparams import HParams
  File "/root/project/resemble-enhance/resemble_enhance/hparams.py", line 36, in <module>
    class HParams:
  File "/root/project/resemble-enhance/resemble_enhance/hparams.py", line 105, in HParams
    def load(cls, run_dir, yaml: Path | None = None):
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
(voice_enhance) root@jack-B450M-S2H:~/project/resemble-enhance# ls
LICENSE  README.md  app.py  config  packages.txt  pyproject.toml  requirements.txt  resemble_enhance  setup.py
(voice_enhance) root@jack-B450M-S2H:~/project/resemble-enhance# resemble-enhance 
Traceback (most recent call last):
  File "/root/anaconda3/envs/voice_enhance/bin/resemble-enhance", line 33, in <module>
    sys.exit(load_entry_point('resemble-enhance==0.0.1', 'console_scripts', 'resemble-enhance')())
  File "/root/anaconda3/envs/voice_enhance/bin/resemble-enhance", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/root/anaconda3/envs/voice_enhance/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/root/anaconda3/envs/voice_enhance/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/anaconda3/envs/voice_enhance/lib/python3.9/site-packages/resemble_enhance-0.0.1-py3.9.egg/resemble_enhance/enhancer/__main__.py", line 10, in <module>
    from .inference import denoise, enhance
  File "/root/anaconda3/envs/voice_enhance/lib/python3.9/site-packages/resemble_enhance-0.0.1-py3.9.egg/resemble_enhance/enhancer/inference.py", line 6, in <module>
    from ..inference import inference
  File "/root/anaconda3/envs/voice_enhance/lib/python3.9/site-packages/resemble_enhance-0.0.1-py3.9.egg/resemble_enhance/inference.py", line 11, in <module>
    from .hparams import HParams
  File "/root/anaconda3/envs/voice_enhance/lib/python3.9/site-packages/resemble_enhance-0.0.1-py3.9.egg/resemble_enhance/hparams.py", line 36, in <module>
    class HParams:
  File "/root/anaconda3/envs/voice_enhance/lib/python3.9/site-packages/resemble_enhance-0.0.1-py3.9.egg/resemble_enhance/hparams.py", line 105, in HParams
    def load(cls, run_dir, yaml: Path | None = None):
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```
2. I use the pip install the package named resemble-enhance,and when I use it to enhance a wav file,it meets errors.
```bash
(base) root@jack-B450M-S2H:/mnt/disk1/test/audio# resemble-enhance input/ output/
[2024-02-08 08:40:35,596] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
CUDA is not available but --device is set to cuda, using CPU instead
Processing output/part2.wav:   0%|                                                                                                                          | 0/1 [04:29<?, ?it/s]
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/root/anaconda3/lib/python3.11/http/client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/root/anaconda3/lib/python3.11/http/client.py", line 1332, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/root/anaconda3/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/root/anaconda3/lib/python3.11/http/client.py", line 1041, in _send_output
    self.send(msg)
  File "/root/anaconda3/lib/python3.11/http/client.py", line 979, in send
    self.connect()
  File "/root/anaconda3/lib/python3.11/http/client.py", line 1451, in connect
    super().connect()
  File "/root/anaconda3/lib/python3.11/http/client.py", line 945, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/root/anaconda3/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/bin/resemble-enhance", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/resemble_enhance/enhancer/__main__.py", line 110, in main
    hwav, sr = enhance(
               ^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/resemble_enhance/enhancer/inference.py", line 39, in enhance
    enhancer = load_enhancer(run_dir, device)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/resemble_enhance/enhancer/inference.py", line 16, in load_enhancer
    run_dir = download()
              ^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/resemble_enhance/enhancer/download.py", line 27, in download
    torch.hub.download_url_to_file(url, str(path))
  File "/root/anaconda3/lib/python3.11/site-packages/torch/hub.py", line 620, in download_url_to_file
    u = urlopen(req)
        ^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out
```

- btw, i download the resemble-enhance package in a virtual environment with python3.10 because the python3.9 will return other error 
```bash
(voice_enhance) root@jack-B450M-S2H:~/project/resemble-enhance# resemble-enhance 
Traceback (most recent call last):
  File "/root/anaconda3/envs/voice_enhance/bin/resemble-enhance", line 33, in <module>
    sys.exit(load_entry_point('resemble-enhance==0.0.1', 'console_scripts', 'resemble-enhance')())
  File "/root/anaconda3/envs/voice_enhance/bin/resemble-enhance", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/root/anaconda3/envs/voice_enhance/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/root/anaconda3/envs/voice_enhance/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/anaconda3/envs/voice_enhance/lib/python3.9/site-packages/resemble_enhance-0.0.1-py3.9.egg/resemble_enhance/enhancer/__main__.py", line 10, in <module>
    from .inference import denoise, enhance
  File "/root/anaconda3/envs/voice_enhance/lib/python3.9/site-packages/resemble_enhance-0.0.1-py3.9.egg/resemble_enhance/enhancer/inference.py", line 6, in <module>
    from ..inference import inference
  File "/root/anaconda3/envs/voice_enhance/lib/python3.9/site-packages/resemble_enhance-0.0.1-py3.9.egg/resemble_enhance/inference.py", line 11, in <module>
    from .hparams import HParams
  File "/root/anaconda3/envs/voice_enhance/lib/python3.9/site-packages/resemble_enhance-0.0.1-py3.9.egg/resemble_enhance/hparams.py", line 36, in <module>
    class HParams:
  File "/root/anaconda3/envs/voice_enhance/lib/python3.9/site-packages/resemble_enhance-0.0.1-py3.9.egg/resemble_enhance/hparams.py", line 105, in HParams
    def load(cls, run_dir, yaml: Path | None = None):
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by aryamtos** [comment]
The error is due to the use of the |  operator, which is available only in Python 3.10 and later. In Python 3.9 the operator is not supported instead you should use '**Optional**, '**Union**' type from the '**typing**' module. [https://docs.python.org/3/library/typing.html](url)


In TimeoutError, indicates that the script is attempting to make a network request, ensure your connection is stable. Additionally, the message **CUDA is not available but --device is set to cuda, using CPU instead**, indicates that CUDA isn't properly set up. Check if CUDA is available:

```
import torch
print(torch.cuda.is_available())
```
