### ISSUE TITLE
Command line error

### ISSUE THREAD

**Issue by ddegner** [resemble-ai/resemble-enhance#21]
I'm using this great app on an Apple M1.

I used a virtual environment to run it in Python 3.10.  After it has been installed the Web App works great.  But when I try to run the command line version I get a cascade of errors.

This occurs on the dev and main branch, in Python 3.10 and 3.11

```
(my_env) degner@Davids-MacBook-Pro-2 Desktop % resemble-enhance /Users/degner/Desktop/To\ Clean /Users/degner/Desktop/Cleaned
[2024-03-02 00:32:41,743] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to mps (auto detect)
[2024-03-02 00:32:41,850] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
CUDA is not available but --device is set to cuda, using CPU instead
Processing /Users/degner/Desktop/Cleaned/Main - synced 2 - Cut down 2 copy.wav:   0%|                                                                                                                                                                                         | 0/2 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/Users/degner/Desktop/my_env/bin/resemble-enhance", line 8, in <module>
    sys.exit(main())
  File "/Users/degner/Desktop/my_env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/degner/Desktop/my_env/lib/python3.10/site-packages/resemble_enhance/enhancer/__main__.py", line 110, in main
    hwav, sr = enhance(
  File "/Users/degner/Desktop/my_env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/degner/Desktop/my_env/lib/python3.10/site-packages/resemble_enhance/enhancer/inference.py", line 39, in enhance
    enhancer = load_enhancer(run_dir, device)
  File "/Users/degner/Desktop/my_env/lib/python3.10/site-packages/resemble_enhance/enhancer/inference.py", line 20, in load_enhancer
    state_dict = torch.load(path, map_location="cpu")["module"]
  File "/Users/degner/Desktop/my_env/lib/python3.10/site-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Users/degner/Desktop/my_env/lib/python3.10/site-packages/torch/serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
(my_env) degner@Davids-MacBook-Pro-2 Desktop % 

```

**Comment by JonathanBonnaud** [comment]
Hello, was anyone able to resolve it?

**Comment by sudecki30** [comment]
Hi, you need to install `sudo apt-get install git-lfs`

After you go to `.../python3.10/site-packages/resemble_enhance/model_repo`

And you go `git clone https://huggingface.co/ResembleAI/resemble-enhance`

By default git don't download large file, you need to install a specific version for. (download.py is not working)
