### ISSUE TITLE
RuntimeError in torchaudio_sox::load_audio_file()

### ISSUE THREAD

**Issue by kgoba** [resemble-ai/resemble-enhance#27]
`torchaudio_sox::load_audio_file()` seems to expect str, not PosixPath (not sure why though):

```Processing tmp/myfile.wav:   0%|                                                                          | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/bwords/Devel/nightingale/./venv/bin/resemble-enhance", line 8, in <module>
    sys.exit(main())
  File "/Users/bwords/Devel/nightingale/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/bwords/Devel/nightingale/venv/lib/python3.10/site-packages/resemble_enhance/enhancer/__main__.py", line 94, in main
    dwav, sr = torchaudio.load(path)
  File "/Users/bwords/Devel/nightingale/venv/lib/python3.10/site-packages/torchaudio/_backend/utils.py", line 205, in load
    return backend.load(uri, frame_offset, num_frames, normalize, channels_first, format, buffer_size)
  File "/Users/bwords/Devel/nightingale/venv/lib/python3.10/site-packages/torchaudio/_backend/sox.py", line 44, in load
    ret = sox_ext.load_audio_file(uri, frame_offset, num_frames, normalize, channels_first, format)
  File "/Users/bwords/Devel/nightingale/venv/lib/python3.10/site-packages/torch/_ops.py", line 755, in __call__
    return self._op(*args, **(kwargs or {}))
RuntimeError: torchaudio_sox::load_audio_file() Expected a value of type 'str' for argument '_0' but instead found type 'PosixPath'.
Position: 0```

**Comment by vanliyan** [comment]
You can temporary fix this by casting your path to str.
`path = str(path)`

The project still will not work because it needs Cuda.

**Comment by vanliyan** [comment]
You can temporary fix this by casting the path to str.
`path = str(path)`

**Comment by vanliyan** [comment]
> You can temporary fix this by casting the path to str. `path = str(path)`

Also be careful that you need to actually do the same for `torchaudio::sox_io_save_audio_file()` too, otherwise you waste your time and won't be able to save the conversion.
