### ISSUE TITLE
Is an Nvidia GPU required?

### ISSUE THREAD

**Issue by sorenss** [resemble-ai/resemble-enhance#32]
I guessed that I had to install git-lfs, which made the code work for a bit longer. But Now I am getting:
"RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx"

I am on Kubuntu 22.04, with an AMD gpu, and no Nvidia in this machine. If that's required it would be nice to state that somewhere? Full output is:

```
[2024-06-15 18:29:21,064] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Processing enhanced/ipraaudiowav.wav:   0%|                                                                                                                                               | 0/1 [00:00<?, ?it/s]Already up to date.
Processing enhanced/ipraaudiowav.wav:   0%|                                                                                                                                               | 0/1 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "/home/soren/.local/bin/resemble-enhance", line 8, in <module>
    sys.exit(main())
  File "/home/soren/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/soren/.local/lib/python3.10/site-packages/resemble_enhance/enhancer/__main__.py", line 104, in main
    hwav, sr = enhance(
  File "/home/soren/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/soren/.local/lib/python3.10/site-packages/resemble_enhance/enhancer/inference.py", line 39, in enhance
    enhancer = load_enhancer(run_dir, device)
  File "/home/soren/.local/lib/python3.10/site-packages/resemble_enhance/enhancer/inference.py", line 23, in load_enhancer
    enhancer.to(device)
  File "/home/soren/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/home/soren/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/soren/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/soren/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/soren/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/home/soren/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/soren/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```

Btw: there's a type in the documentation, using _ instead of - in "resemble-enhance".

**Comment by jmaris** [comment]
you can use CPU with --device=cpu
