### ISSUE TITLE
Exception in ASGI application

### ISSUE THREAD

**Issue by zeta274** [resemble-ai/resemble-enhance#49]
Running the Gradio interface I get:

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/viktor/miniconda3/envs/resemble_enhance/lib/python3.10/site-packages/pydantic/type_adapter.py", line 270, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
  File "/home/viktor/miniconda3/envs/resemble_enhance/lib/python3.10/site-packages/pydantic/type_adapter.py", line 112, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

I can upload files, but when I try to process them this error just repeats over and over.
Python 3.10, running in a Conda, requirements installed without issue
RTX 4090

**Comment by lukeewin** [comment]
> Hi, You need to force upgrade gradio. There is an error with older gradio version using new fastapi (using new pydantic). Check this issue : [gradio-app/gradio#9278](https://github.com/gradio-app/gradio/issues/9278) A simple "pip install -U gradio==4.43.0" worked for me (could be newer version maybe?)

But tip  ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
resemble-enhance 0.0.1 requires gradio==4.8.0, but you have gradio 4.43.0 which is incompatible.

**Comment by SuperFurias** [comment]
> Hi, You need to force upgrade gradio. There is an error with older gradio version using new fastapi (using new pydantic). Check this issue : [gradio-app/gradio#9278](https://github.com/gradio-app/gradio/issues/9278) A simple "pip install -U gradio==4.43.0" worked for me (could be newer version maybe?)

thanks broski, i did "pip install gradio --upgrade" and just to be sure "python.exe -m pip install --upgrade pip" and everything works now
